version: '3.7'

services:
  # PostgreSQL service
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres #Change to data from env file
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
    - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: Doroshkeviches@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
     - postgres
volumes:
  pgdata:
  pgadmin-data:
  


 

